// See dbdiagram.io for rendering and dcoumentation

// This data model is the latest data model from the CMG consortium, at 
// https://docs.google.com/spreadsheets/d/1vq9rGlWzYym0N1WSFeT4vcJqbJOjbP0uDAiffzbl1Fw/edit

// note: this does not include the field definitions or 
// enumarations from that sheet at this time

// Creating tables

// Enumerations for Subject table

Table Subject {
  subject_id varchar [pk, not null]
  family_id varchar [not null] // note: not required by AnVIL
  affected_status varchar // to enum
  age_at_last_observation int
  age_of_onset int
  ancestry varchar // to enum
  ancestry_detail varchar
  congenital_status varchar // to enum
  dbgap_study_id varchar
  dbgap_subject_id varchar
  dbgap_submission bool
  disease_description varchar
  disease_id varchar
  hpo_present varchar
  hpo_absent varchar
  maternal_id varchar
  multiple_datasets bool
  paternal_id varchar
  phenotype_description varchar
  phenotype_group varchar // to enum
  pmid_id int
  prior_testing varchar
  proband_relationship varchar // to enum
  project_id varchar [not null]
  sex varchar // to enum
  solve_state varchar // to enum
  twin_id varchar
  // note: the following are required fields on AnVIL
  // submitter_id varchar [not null]
}

// Enumerations for Sample Table

Table Sample {
  subject_id varchar [not null]
  sample_id varchar [pk, not null]
  dbgap_sample_id varchar [not null]
  sample_source varchar // to enum
  sequencing_center varchar // to enum
  tissue_affected_status bool
}

// Enumerations for Family tables

Table Family {
  family_id varchar [not null]
  consanguinity varchar [not null] // to enum
  consanguinity_detail varchar
  pedigree_image varchar
  pedigree_detail varchar
  family_history varchar // to bool
  family_onset varchar
  
  // note: the following are fields on AnVIL
  // solve_state varchar [not null] // to enum
}

// Enumerations for Discovery Table

Table Discovery {
  subject_id varchar [not null]
  sample_id varchar [not null]
  gene varchar
  gene_class varchar // to enum
  inheritance_description varchar // to enum
  zygosity varchar // to enum
  variant_genome_build varchar
  chrom varchar // to numeric
  pos varchar // to numeric
  ref varchar // to numeric
  alt varchar
  hgvsc varchar
  hgvsp varchar
  transcript varchar
  sv_name varchar
  sv_type varchar // to enum
  signifcance varchar // to enum
  
  // note: the following are required fields on AnVIL
  // discovery_id varchar [pk, not null]
}

// Enumerations for Sequencing Table

Table Sequencing {
  sample_id varchar [not null]
  seq_filename varchar
  analyte_type varchar // to enum
  sequencing_assay varchar // to enum
  library_prep_kit_method varchar
  exome_capture_platform varchar
  capture_region_bed_file varchar
  reference_genome_build varchar
  alignment_method varchar
  data_processing_pipeline varchar
  functional_equivalence_standard varchar
  date_data_generation varchar // to datetime

  // note: the following are required fields on AnVIL
  // sequencing_id varchar [pk, not null]
  // submitter_id varchar [not null]
  // md5sum varchar [not null]
  // file_size varchar [not null]
  // file_name varchar [not null]
  // data_type varchar [not null]

  // note: the following are optional fields on AnVIL model
  // sequencer_id varchar
  // tissue_source varchar
  // sequencing_platform varchar
  // target_insert_size varchar // to int
  // target_depth varchar // to int
  // sequencing_strategy varchar
  // read_length varchar // to int
  // number_of_independent_libraries varchar // to int
  // sex varchar // to enum
}

// references between tables
Ref: Subject.subject_id > Sample.subject_id
Ref: Subject.subject_id > Discovery.subject_id
Ref: Sample.sample_id > Discovery.sample_id
Ref: Subject.family_id > Family.family_id
Ref: Sample.sample_id > Sequencing.sample_id
