// NOTE: THIS IS A DRAFT/PROPOSAL DATA MODEL

// See dbdiagram.io for rendering and dcoumentation
// Current rendering is at
// https://dbdiagram.io/d/61d4dc323205b45b73d71d9b

// This data model is a draft to facilitate discussion of
// biosample fields, as drafted here:
// https://docs.google.com/spreadsheets/d/1tZ5zrR9h4LR9nkOl-L9wzoVufpEhmeGQ6lz_XsuWkBg/edit
//
// other tables are included here:
// https://docs.google.com/spreadsheets/d/1uEH0UVv-7wsiQ4sY4FykJRmSae17swXxcDIsKHtUx-0/edit#

// note: this does not include the field definitions, types, or 
// enumarations

// Creating tables

// Enumerations for Subject table

// to enum gregor_center
// to enum data_use_limitations
// to enum proband_relationship

enum subject_sex {
  Female
  Male
  Unknown
}

enum subject_race {
  American Indian or Alaska Native
  Asian
  Black or African American
  Native Hawaiian or Other Pacific Islander
  Middle Eastern or North African(*??)
  White
  Unknown
}

enum subject_ethnicity {
  Hispanic or Latino
  Not Hispanic or Latino
  Unknown
}

// to enum phenotype_group

enum subject_affected {
  Affected
  Unaffected
  Possibly affected
  Unknown
}

enum subject_solve {
  Unsolved
  Tier 2
  Tier 1
}

Table Subject {
  subject_id varchar [pk, not null,
    note: 'subject/participant identifier'
  ]
  project_id varchar [not null,
    note: 'information field about cohort'
  ] // to expand description
  submitter_id varchar [not null,
    note: 'a project-specific identifier for a node'
  ] // to expand description
  gregor_center varchar [
    note: 'GREGoR Center to which the participant is originally associated'
  ] // to enum
  data_use_limitations varchar [
    note: 'consent group pertaining to this participant's data'
  ] // to enum
  recontactable bool [
    note: 'is the originating GREGoR Center likely able to recontact this participant'
  ]
  prior_testing varchar [
    note: 'text description of any genetic testing for individual conducted prior to enrollment'
  ]
  pmid_id int [
    note: 'case specific PubMed ID if applicable'
  ]
  dbgap_submission bool [
    note: 'flag if sample has been submitted to dbGaP'
  ]
  dbgap_study_id varchar [
    note: 'phs ID/accession for study'
  ]
  dbgap_subject_id varchar [
    note: 'subject identifier used in dbGaP (if previously submitted)'
  ]
  multiple_datasets bool [
    note: 'flag if an individual has data represented in multiple data types'
  ] // to expand description
  family_id varchar [
    note: 'identifier for family'
  ]
  paternal_id varchar [
    note: 'subject_id for father'
  ]
  maternal_id varchar [
    note: 'subject_id for mother'
  ]
  twin_id varchar [
    note: 'subject_id for twins, triplets, etc'
  ]
  proband_relationship varchar [
    note: 'text description of individual relationship to proband in family, especially useful to capture relationships when connecting distant relatives and connecting relatives not studied'
  ] // to enum
  proband_relationship_other varchar [
    note: 'other proband relationship not captured in enumeration above'
  ]
  sex subject_sex [
    note: 'Biological sex assigned at birth (aligned with All of Us). If individual has a known DSD / not expected sex chromosome karyotype, this can be noted in the phenotype information section.'
  ]
  sex_detail varchar [
    note: 'optional free-text field to describe known discrepancies between 'sex' value (female=>XX, male=>XY) and actual sex chromosome karyotype'
  ]
  race subject_race [
    note: 'self/submitter-reported race (OMB categories)'
  ]
  ethnicity subject_ethnicity [
    note: 'self/submitter-reported ethnicity (OMB categories)'
  ]
  ancestry_detail varchar [
    note: 'additional specific ancestry description free text beyond what is captured by OMB race/ethnicity categories'
  ]
  age_at_last_observation int [
    note: 'age at last observation'
  ] // to expand description
  phenotype_group varchar [
    note: 'optional submitter-defined field for individuals that could be grouped together in a single analysis based on overlap in phenotypic features'
  ] // to enum
  disease_id varchar [
    note: 'concept code for disease (e.g. OMIM, Orphanet)'
  ]
  disease_description varchar [
    note: 'disease name or free text description of disease (especially if concept code not available)'
  ]
  affected_status subject_affected [
    note: 'indicate affected status of individual (overall with respect to primary phenotype in the family)'
  ]
  phenotype_description varchar [
    note: phenotypic one-line summary for why this individual is of interest'
  ] // to expand description
  solve_state subject_solve [
    note: 'solved state of an individual'
  ]
}

// Enumerations for Sample Table

Table BioSample {
  bio_sample_id varchar [pk, not null]
  subject_id varchar [not null]
  sample_source varchar // to enum
  tissue_affected_status bool
  age_at_collection int
  sample_collection_timestamp datetime
  subject_drugs_intake bool
}

Table Experiments {
  experiment_id varchar [pk, not null]
  assay_type varchar // to enum
  bio_sample_id varchar
}

Table experiment_details_exome_genome {
  experiment_id varchar
  seq_library_prep_kit_method varchar
  read_length varchar
  exome_capture_platform varchar
  exome_capture_region_bed_file varchar
  date_data_generation datetime
  sequencer_id varchar
  sequencing_platform varchar
  target_insert_size varchar
  number_of_independent_libraries varchar
}

Table experiment_details_rna_seq {
  experiment_id varchar
  seq_library_prep_kit_method varchar
  read_length varchar
}

table experiment_details_mass_spec {
  experiment_id varchar
  proteomics_quantitation_method varchar
  proteomics_analystical_fraction varchar
  timepoint varchar
  
}

table raw_data_files_exome_genome {
  experiment_id varchar
  filename varchar
  md5sum varchar
  file_size varchar
  reference_genome_build varchar
  alignment_method varchar
}

table processed_data_files_exome_genome {
  raw_data_source_filename varchar
  filename varchar
  md5sum varchar
  file_size varchar
  caller varchar
}

table raw_data_files_rna_seq {
  experiment_id varchar
  filename varchar
  md5sum varchar
  file_size varchar
  reference_genome_build varchar
  alignment_method varchar
}

table processed_data_files_rna_seq {
  raw_data_source_filename varchar
  filename varchar
  md5sum varchar
  file_size varchar
  caller varchar
}

table raw_data_files_mass_spec {
  experiment_id varchar
  filename varchar
  md5sum varchar
  file_size varchar
  machine varchar
  software varchar
}

table processed_data_files_mass_spec {
  raw_data_source_filename varchar
  filename varchar
  md5sum varchar
  file_size varchar
}

// Enumerations for Family tables

enum family_solve {
  Unsolved
  Tier 2
  Tier 1
}

enum family_consanguinity {
  None suspected
  Suspected
  Present
  Unknown
}

Table Family {
  family_id varchar [pk, ref: < Subject.family_id, not null,
    note: 'identifier for family (needs to be Unique across centers, can consider prefix for each center if needed)'
  ]
  solve_state family_solve [not null,
    note: 'solved state of a family'
  ]
  consanguinity family_consanguinity [not null,
    note: 'indicate if consanguinity is present or suspected within a family'
  ]
  consanguinity_detail varchar [
    note: 'free text description of any additional consanguinity details'
  ]
  pedigree_file varchar [
    note: 'name of file (can contain a PED file or image)'
  ]
  pedigree_detail varchar [
    note: 'free text description of other family structure/pedigree image caption or additional phenotypic information from family members who are not participating in the study'
  ]
  family_history varchar [
    note: 'flag if there is a known family history for the phenotype'
  ] // to bool and expand description
  family_onset varchar [
    note: 'information regarding typical age of onset for affected individuals in family if relevant for phenotype' 
  ]
}

// Enumerations for Phenotype tables

enum pheno_presence {
  present
  absent
  unknown
}

enum pheno_ontology {
  HPO
  MONDO
  OMIM
  ORPHANET
  SNOMED
}

enum pheno_onsent {
  Unknown
  Congenital onset [note: 'HP:0003577']
  Embryonal onset 
  Fetal onset
  Neonatal onset 
  Infantile onset
  Childhood onset
  Juvenile onset
  Adult onset 
  Young adult onset
  Middle age onset 
  Late onset
}

Table phenotype {
  subject_id varchar [pk, ref: - Subject.subject_id, not null,
    note: 'subject/participant identifier within project'
  ]
  term_id varchar [
    note: 'identifier for HPO term or other ontology term'
  ] // to expand description
  presence pheno_presence [not null,
    note: 'defines if this term is present or absent in this subject'
  ]
  ontology pheno_ontology [
    note: 'ontology source of the term_id'
  ]
  additional_details varchar [
    note: 'additional information relevant to the term but not capturable in the identifier ontology'
  ] // to expand description
  onsent_age_range pheno_onset [not null,
    note: 'age of onsent bucket range (if affected with non-congenital feature)'
  ]
  additional_modifiers varchar [
   note: 'additional clinical modifiers from HPO (e.g. rapid progression)'
  ] // potentially add delimited list of valid HPO IDs that are subordinate to HP:0012823
}

// references between tables
Ref: Subject.subject_id > BioSample.subject_id
Ref: Subject.family_id > Family.family_id // moved up to family table

Ref: "Experiments"."bio_sample_id" < "BioSample"."bio_sample_id"

Ref: "experiment_details_mass_spec"."experiment_id" < "Experiments"."experiment_id"

Ref: "experiment_details_exome_genome"."experiment_id" < "Experiments"."experiment_id"

Ref: "experiment_details_rna_seq"."experiment_id" < "Experiments"."experiment_id"

Ref: "raw_data_files_exome_genome"."experiment_id" < "experiment_details_exome_genome"."experiment_id"

Ref: "raw_data_files_rna_seq"."experiment_id" < "experiment_details_rna_seq"."experiment_id"

Ref: "raw_data_files_mass_spec"."experiment_id" < "experiment_details_mass_spec"."experiment_id"

Ref: "processed_data_files_mass_spec"."raw_data_source_filename" < "raw_data_files_mass_spec"."filename"

Ref: "processed_data_files_rna_seq"."raw_data_source_filename" < "raw_data_files_rna_seq"."filename"

Ref: "processed_data_files_exome_genome"."raw_data_source_filename" < "raw_data_files_exome_genome"."filename"

Ref: "phenotype"."subject_id" < "Subject"."subject_id" // moved up to phenotype table
