on:
  pull_request:
    branches: [ "master", "main" ]

  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        data_model_file: [
          'GREGoR_data_model.json',
        ]
    name: Check data model
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.2.3"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: github::UW-GAC/AnvilDataModels, any::sessioninfo
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Check ${{ matrix.data_model_file }} file
        run: |
          AnvilDataModels::json_to_dm("${{ matrix.data_model_file }}")
        shell: Rscript {0}
